# Generated by Django 5.2.17 on 2026-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password reset'), ('registration', 'Registration')], max_length=20),
        ),
    ]
