"""
Django settings for ecommernce project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import copy
import django.template.context

# Compatibility patch for Python 3.13/3.14+ regarding BaseContext.__copy__ AttributeError
def django_context_copy_patch(self):
    cls = self.__class__
    duplicate = cls.__new__(cls)
    for key, val in self.__dict__.items():
        if key != 'dicts':
            duplicate.__dict__[key] = val
    duplicate.dicts = self.dicts[:]
    return duplicate

django.template.context.BaseContext.__copy__ = django_context_copy_patch

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env variables
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


# Production is the default: local development opts in with DEBUG=True in .env.
DEBUG = env_bool('DEBUG', False)
TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG or TESTING:
        SECRET_KEY = 'django-insecure-local-development-only'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set in the environment when DEBUG is False.')

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', '127.0.0.1,localhost')

# Origins allowed to submit session/CSRF-protected requests. Defaults to
# https:// for each real host in ALLOWED_HOSTS (plus http:// in DEBUG).
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')
if not CSRF_TRUSTED_ORIGINS:
    for host in ALLOWED_HOSTS:
        if host not in ('127.0.0.1', 'localhost', '*'):
            CSRF_TRUSTED_ORIGINS.append(f"https://{host.lstrip('.')}")
            if DEBUG:
                CSRF_TRUSTED_ORIGINS.append(f"http://{host.lstrip('.')}")

# HTTPS / cookie security. Secure cookies follow DEBUG by default; the
# redirect/HSTS/proxy settings depend on the hosting setup, so they are
# opt-in via environment variables.
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
# Behind a TLS-terminating proxy/load balancer (Heroku, Render, Nginx…) set
# SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO so request.is_secure() and
# absolute media URLs use https://. Only set it if the proxy strips/sets the header.
if os.getenv('SECURE_PROXY_SSL_HEADER'):
    SECURE_PROXY_SSL_HEADER = (os.getenv('SECURE_PROXY_SSL_HEADER'), 'https')



# Application definition

INSTALLED_APPS = [
    'daphne',  # Channels ASGI server
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', 
    
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt', # JWT support
    'rest_framework_simplejwt.token_blacklist',
    
    # Allauth Apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # Local apps
    'shop.apps.ShopConfig',
    'accounts',
    'adminpanel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Account middleware for allauth
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'ecommernce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom processor for dynamic navbar values
                'shop.context_processors.cart_summary',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommernce.wsgi.application'


# Database
# Use PostgreSQL if credentials exist in environment, else fallback to SQLite

DB_NAME = os.getenv('DB_NAME')
if DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static and Media files
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Static files are served by WhiteNoise in production (run collectstatic at
# build time). The hashed manifest storage needs collectstatic to have run,
# so it's used only outside DEBUG/test runs unless overridden.
STATIC_MANIFEST = env_bool('STATIC_MANIFEST', not DEBUG and not TESTING)
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage' if STATIC_MANIFEST
        else 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', BASE_DIR / 'media'))
# Uploaded product images. With DEBUG=False Django does not serve them unless
# SERVE_MEDIA=True (single-server deployments with a persistent disk). For
# multi-instance or ephemeral-filesystem hosting, use object storage instead.
SERVE_MEDIA = env_bool('SERVE_MEDIA', DEBUG)

# Cache configuration (Redis support)
REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Allauth configurations
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none' # Local signup is closed (see ACCOUNT_ADAPTER); applies to social logins only
# Customer self-registration goes through /api/accounts/register/ (email OTP).
# allauth's own /accounts/signup/ would bypass that, so it is closed.
ACCOUNT_ADAPTER = 'accounts.adapters.NoLocalSignupAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.OpenSocialSignupAdapter'
ACCOUNT_SESSION_REMEMBER = True     # Config for "Remember Me"
SOCIALACCOUNT_LOGIN_ON_GET = True   # Skip intermediate social login confirmation page

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}


# Email System Configuration
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
# SMTP credentials come only from the environment — never from source code.
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").replace(" ", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", f"Shopping_App <{EMAIL_HOST_USER}>" if EMAIL_HOST_USER else "Shopping_App <no-reply@localhost>")


# DRF configurations with SimpleJWT support
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    # Number of trusted reverse proxies in front of the app. 0 = use the
    # direct peer address, so clients can't spoof X-Forwarded-For to evade
    # throttling. Set to 1 behind a single proxy/load balancer.
    'NUM_PROXIES': int(os.getenv('NUM_PROXIES', '0')),
    # Applied per view via `throttle_scope` (auth, payments).
    'DEFAULT_THROTTLE_RATES': {
        'auth': os.getenv('THROTTLE_AUTH_RATE', '20/min'),
        'payments': os.getenv('THROTTLE_PAYMENTS_RATE', '30/min'),
    },
}

# CORS — the bundled frontend is same-origin; list any separate frontend
# origins (e.g. https://shop.example.com) in CORS_ALLOWED_ORIGINS.
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]
CORS_URLS_REGEX = r'^/api/.*$'

# Payment gateway (Razorpay). Use rzp_test_* keys for test mode.
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')
# Secret configured on the Razorpay dashboard webhook (Settings → Webhooks).
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', '')

# Unpaid PENDING orders older than this are cancelled by
# `python manage.py expire_pending_orders` (schedule it, e.g. every 15 min).
PENDING_ORDER_TIMEOUT_MINUTES = int(os.getenv('PENDING_ORDER_TIMEOUT_MINUTES', '60'))

# Checkout pricing rules (INR). A flat delivery charge that is waived once
# the discounted item total reaches FREE_DELIVERY_MIN_ORDER. 0 disables.
DELIVERY_CHARGE = os.getenv('DELIVERY_CHARGE', '0')
FREE_DELIVERY_MIN_ORDER = os.getenv('FREE_DELIVERY_MIN_ORDER', '0')

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Channels Configuration
ASGI_APPLICATION = 'ecommernce.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.getenv('REDIS_URL', 'redis://localhost:6379')],
        },
    }
}

# Fallback to in-memory channels for development without Redis
if not os.getenv('REDIS_URL'):
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }

# Session Management Settings - Enforce mandatory login on browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = True



